model_config_list: {
    config: {
        name: "root",
        base_path: "/home/brandon/Documents/Forge/forgeai-ai/HierarchicalClassifier/models/servables/nuclear_test",
        model_platform: "tensorflow"
    },
    config: {
        name: "general",
        base_path: "/home/brandon/Documents/Forge/forgeai-ai/HierarchicalClassifier/models/servables/nuclear_test__05--Fuel-Fabrication",
        model_platform: "tensorflow"
    }
}