model_config_list: {
	config: {
		name: "nuclear_test__05--Fuel-Fabrication__06--Reactors__08--Reprocessing__03--Enrichment",
		base_path: "/home/brandon/Documents/Forge/forgeai-ai/HierarchicalClassifier/models/servables/nuclear_test__05--Fuel-Fabrication__06--Reactors__08--Reprocessing__03--Enrichment",
		model_platform: "tensorflow"
	},
	config: {
		name: "nuclear_test__05--Fuel-Fabrication__06--Reactors",
		base_path: "/home/brandon/Documents/Forge/forgeai-ai/HierarchicalClassifier/models/servables/nuclear_test__05--Fuel-Fabrication__06--Reactors",
		model_platform: "tensorflow"
	},
	config: {
		name: "nuclear_test__05--Fuel-Fabrication__06--Reactors__08--Reprocessing",
		base_path: "/home/brandon/Documents/Forge/forgeai-ai/HierarchicalClassifier/models/servables/nuclear_test__05--Fuel-Fabrication__06--Reactors__08--Reprocessing",
		model_platform: "tensorflow"
	},
	config: {
		name: "nuclear_test",
		base_path: "/home/brandon/Documents/Forge/forgeai-ai/HierarchicalClassifier/models/servables/nuclear_test",
		model_platform: "tensorflow"
	},
	config: {
		name: "nuclear_test__05--Fuel-Fabrication",
		base_path: "/home/brandon/Documents/Forge/forgeai-ai/HierarchicalClassifier/models/servables/nuclear_test__05--Fuel-Fabrication",
		model_platform: "tensorflow"
	},
	config: {
		name: "nuclear_test__05--Fuel-Fabrication__06--Reactors__08--Reprocessing__03--Enrichment__5-4--Fuel-for-Research-and-Test-Reactors",
		base_path: "/home/brandon/Documents/Forge/forgeai-ai/HierarchicalClassifier/models/servables/nuclear_test__05--Fuel-Fabrication__06--Reactors__08--Reprocessing__03--Enrichment__5-4--Fuel-for-Research-and-Test-Reactors",
		model_platform: "tensorflow"
	},
	config: {
		name: "nuclear_test__05--Fuel-Fabrication__06--Reactors__08--Reprocessing__03--Enrichment__5-4--Fuel-for-Research-and-Test-Reactors__3-1--Enrichment-of-UF6",
		base_path: "/home/brandon/Documents/Forge/forgeai-ai/HierarchicalClassifier/models/servables/nuclear_test__05--Fuel-Fabrication__06--Reactors__08--Reprocessing__03--Enrichment__5-4--Fuel-for-Research-and-Test-Reactors__3-1--Enrichment-of-UF6",
		model_platform: "tensorflow"
	}
}